### ISSUE TITLE
Please archive all unmaintained styles =)

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/IRCCloud-Dark#7]

**Comment by silverwind** [comment]
Can a archived repo be unarchived later?

**Comment by the-j0k3r** [comment]
Yes, according to https://help.github.com/en/articles/archiving-repositories

Also its recommended to close all issues prs etc https://help.github.com/en/articles/about-archiving-repositories

**Comment by the-j0k3r** [comment]
since no action and I lost interest...
